export const FETCH_RECIPES_REQUEST = "GET_RECIPES";
export const FETCH_RECIPES_REQUEST_SUCCESS = "FETCH_RECIPES_REQUEST_SUCCESS";
export const FETCH_RECIPES_REQUEST_FAILURE = "FETCH_RECIPES_REQUEST_FAILURE";
